In [1]:
import pandas as pd

# Load your data
data = pd.read_excel('../data/Data_MNL_all.xlsx')  # Replace with your file path

# Display the first few rows of the dataset for an initial assessment
data.head()

,driver_id,bhv_app_map,ind_age,ind_fam_number,ind_income_indiv,bhv_other_platform,bhv_online_hour,bhv_longtime_driver,loc_market,loc_school,...,loc_pickup,loc_population,loc_house_bld,loc_parks,loc_office,trip_order_Food,trip_order_delivery,trip_order_Ride,loc_health,location_code
0,ikialink8@gmail.com,3,34,4,3499999.5,False,9,4,1,7,...,625,13297,1014,0,6,False,False,True,2,145
1,ikialink8@gmail.com,3,34,4,3499999.5,False,9,4,1,7,...,128,7522,1328,0,4,False,False,True,0,133
2,ikialink8@gmail.com,3,34,4,3499999.5,False,9,4,0,11,...,147,10254,1419,0,15,False,False,True,1,111
3,ikialink8@gmail.com,3,34,4,3499999.5,False,9,4,0,5,...,262,20196,2186,1,10,True,False,False,3,86
4,ikialink8@gmail.com,3,34,4,3499999.5,False,9,4,1,9,...,245,13023,2232,0,2,False,True,False,1,79

In [3]:
#import numpy as np

# Number of locations in the choice set
num_locations = 151

# Selecting a subset of the data for demonstration (first few unique drivers)
unique_drivers = data['driver_id'].unique()[:5]
subset_data = data[data['driver_id'].isin(unique_drivers)]

# Creating a new DataFrame for the long format
long_format_data = pd.DataFrame()

# Placeholder values for the two missing locations
# Here, using median or mean of existing values can be a good strategy
placeholder_values = {col: subset_data[col].median() for col in subset_data.columns if col.startswith('loc_')}
placeholder_values['location_code'] = 0  # Initializing this to 0 for now


for driver in unique_drivers:
    # Filter data for the current driver
    driver_data = subset_data[subset_data['driver_id'] == driver]

    # Create a DataFrame for all 151 locations for this driver
    driver_choices = pd.DataFrame({
        'driver_id': driver,
        'location_code': range(1, num_locations + 1)
    })

    # Initialize location features with placeholder values
    for col, value in placeholder_values.items():
        driver_choices[col] = value

    # Map location features from the driver data to each choice
    for _, row in driver_data.iterrows():
        for col in row.index:
            if col.startswith('loc_'):
                driver_choices.loc[driver_choices['location_code'] == row['location_code'], col] = row[col]

    # Include a Choice Indicator
    driver_choices['Chosen'] = driver_choices['location_code'].isin(driver_data['location_code'].values).astype(int)

    # Append to the long format data
    long_format_data_corrected = long_format_data_corrected.append(driver_choices, ignore_index=True)

# Displaying the first few rows of the long format data
long_format_data_corrected.head()

AttributeError: 'DataFrame' object has no attribute 'append'